version: 2
project_name: lettercli

before:
  hooks:
    - go mod tidy

builds:
  - id: lettercli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
    main: ./cmd/letterbox-cli/
    binary: lettercli
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: lettercli-archives
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - src: "./dist_py/{{ .Os }}_{{ .Arch }}/*"
        dst: "./py_execs/"
        info:
           mode: 0755
        strip_parent: true

checksum:
  name_template: "checksums.txt"

snapshot: {} 

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: anshonweb 
    name: letterbox-cli  

